"""postgis_y_modelos_dga

Revision ID: 0b902f51a807
Revises: d4e8f9a1b2c3
Create Date: 2026-06-10 01:23:48.876515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b902f51a807'
down_revision: Union[str, Sequence[str], None] = 'd4e8f9a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decretos_escasez',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_decreto', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_index('idx_decretos_escasez_geometria', 'decretos_escasez', ['geometria'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_decretos_escasez_id'), 'decretos_escasez', ['id'], unique=False, if_not_exists=True)
    op.create_table('subcuencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('cuenca_id', sa.Integer(), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cuenca_id'], ['cuencas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_index('idx_subcuencas_geometria', 'subcuencas', ['geometria'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_subcuencas_codigo'), 'subcuencas', ['codigo'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_subcuencas_cuenca_id'), 'subcuencas', ['cuenca_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_subcuencas_id'), 'subcuencas', ['id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_subcuencas_nombre'), 'subcuencas', ['nombre'], unique=False, if_not_exists=True)
    # op.drop_table('spatial_ref_sys')  # NO tocar: tabla interna de la extensión PostGIS
    op.alter_column('consultas_territoriales', 'poligono',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               existing_nullable=False)
    op.alter_column('consultas_territoriales', 'bbox',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('consultas_territoriales', 'resultado_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_consultas_territoriales_created_at'), table_name='consultas_territoriales')
    op.create_index('idx_consultas_territoriales_poligono', 'consultas_territoriales', ['poligono'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.alter_column('cuencas', 'geometria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.create_index('idx_cuencas_geometria', 'cuencas', ['geometria'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.alter_column('eventos_incendio', 'geometria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.create_index('idx_eventos_incendio_geometria', 'eventos_incendio', ['geometria'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.alter_column('fuentes_hidricas', 'geometria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.create_index('idx_fuentes_hidricas_geometria', 'fuentes_hidricas', ['geometria'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.alter_column('indicadores_climaticos', 'datos_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('indicadores_vegetacion', 'datos_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('indices_sequia', 'datos_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('parcelas', 'poligono_vertices',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('resultados_consulta_modulos', 'datos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('resultados_consulta_modulos', 'fuentes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('resultados_consulta_modulos', 'avanzado',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('resultados_consulta_modulos_consulta_id_fkey'), 'resultados_consulta_modulos', type_='foreignkey')
    op.create_foreign_key(None, 'resultados_consulta_modulos', 'consultas_territoriales', ['consulta_id'], ['id'])
    op.add_column('usuarios', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('usuarios', 'is_verified')
    op.drop_constraint(None, 'resultados_consulta_modulos', type_='foreignkey')
    op.create_foreign_key(op.f('resultados_consulta_modulos_consulta_id_fkey'), 'resultados_consulta_modulos', 'consultas_territoriales', ['consulta_id'], ['id'], ondelete='CASCADE')
    op.alter_column('resultados_consulta_modulos', 'avanzado',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('resultados_consulta_modulos', 'fuentes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('resultados_consulta_modulos', 'datos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('parcelas', 'poligono_vertices',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('indices_sequia', 'datos_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('indicadores_vegetacion', 'datos_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('indicadores_climaticos', 'datos_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_fuentes_hidricas_geometria', table_name='fuentes_hidricas', postgresql_using='gist')
    op.alter_column('fuentes_hidricas', 'geometria',
               existing_type=geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_eventos_incendio_geometria', table_name='eventos_incendio', postgresql_using='gist')
    op.alter_column('eventos_incendio', 'geometria',
               existing_type=geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_cuencas_geometria', table_name='cuencas', postgresql_using='gist')
    op.alter_column('cuencas', 'geometria',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_consultas_territoriales_poligono', table_name='consultas_territoriales', postgresql_using='gist')
    op.create_index(op.f('ix_consultas_territoriales_created_at'), 'consultas_territoriales', ['created_at'], unique=False)
    op.alter_column('consultas_territoriales', 'resultado_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('consultas_territoriales', 'bbox',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('consultas_territoriales', 'poligono',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_subcuencas_nombre'), table_name='subcuencas')
    op.drop_index(op.f('ix_subcuencas_id'), table_name='subcuencas')
    op.drop_index(op.f('ix_subcuencas_cuenca_id'), table_name='subcuencas')
    op.drop_index(op.f('ix_subcuencas_codigo'), table_name='subcuencas')
    op.drop_index('idx_subcuencas_geometria', table_name='subcuencas', postgresql_using='gist')
    op.drop_table('subcuencas')
    op.drop_index(op.f('ix_decretos_escasez_id'), table_name='decretos_escasez')
    op.drop_index('idx_decretos_escasez_geometria', table_name='decretos_escasez', postgresql_using='gist')
    op.drop_table('decretos_escasez')
    # ### end Alembic commands ###
