"""Add verification code

Revision ID: 584502578d3a
Revises: 510fe97dcbfd
Create Date: 2026-06-24 01:07:26.095497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
"""Add verification code

Revision ID: 584502578d3a
Revises: 510fe97dcbfd
Create Date: 2026-06-24 01:07:26.095497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '584502578d3a'
down_revision: Union[str, Sequence[str], None] = '510fe97dcbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('verification_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'verification_code')
    # ### end Alembic commands ###
