"""Initial migration with regions comunas and professional structure

Revision ID: 66148a459850
Revises: 
Create Date: 2026-05-25 02:00:13.845679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66148a459850'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, drop the foreign key that references municipios
    op.drop_constraint('agricultores_municipio_id_fkey', 'agricultores', type_='foreignkey')
    
    # Then drop the municipios table
    op.drop_index('ix_municipios_id', table_name='municipios')
    op.drop_index('ix_municipios_nombre', table_name='municipios')
    op.drop_table('municipios')
    
    # Add new columns to agricultores
    op.add_column('agricultores', sa.Column('comuna_id', sa.Integer(), nullable=True))
    op.add_column('agricultores', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('agricultores', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('agricultores', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agricultores', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agricultores', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_agricultores_comuna_id'), 'agricultores', ['comuna_id'], unique=False)
    op.create_foreign_key(None, 'agricultores', 'comunas', ['comuna_id'], ['id'], ondelete='SET NULL')
    op.drop_column('agricultores', 'municipio_id')
    
    # Update balances_hidricos
    op.add_column('balances_hidricos', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('balances_hidricos', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('balances_hidricos', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('balances_hidricos', 'parcela_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_balances_hidricos_fecha'), 'balances_hidricos', ['fecha'], unique=False)
    op.create_index(op.f('ix_balances_hidricos_parcela_id'), 'balances_hidricos', ['parcela_id'], unique=False)
    op.create_index('ix_balances_parcela_fecha', 'balances_hidricos', ['parcela_id', 'fecha'], unique=False)
    op.drop_constraint('balances_hidricos_parcela_id_fkey', 'balances_hidricos', type_='foreignkey')
    op.create_foreign_key(None, 'balances_hidricos', 'parcelas', ['parcela_id'], ['id'], ondelete='CASCADE')
    
    # Update comunas
    op.add_column('comunas', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('comunas', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_comunas_id'), 'comunas', ['id'], unique=False)
    op.create_index(op.f('ix_comunas_nombre'), 'comunas', ['nombre'], unique=False)
    op.create_index(op.f('ix_comunas_region_id'), 'comunas', ['region_id'], unique=False)
    op.create_unique_constraint('uq_comuna_nombre_region', 'comunas', ['nombre', 'region_id'])
    op.drop_constraint('fk_comuna_region', 'comunas', type_='foreignkey')
    op.create_foreign_key(None, 'comunas', 'regiones', ['region_id'], ['id'], ondelete='CASCADE')
    
    # Update parcelas
    op.add_column('parcelas', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('parcelas', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('parcelas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('parcelas', 'latitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('parcelas', 'longitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('parcelas', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('parcelas', 'agricultor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_parcelas_agricultor_id'), 'parcelas', ['agricultor_id'], unique=False)
    op.create_index('ix_parcelas_coordenadas', 'parcelas', ['latitud', 'longitud'], unique=False)
    op.create_index(op.f('ix_parcelas_cultivo'), 'parcelas', ['cultivo'], unique=False)
    op.drop_constraint('parcelas_agricultor_id_fkey', 'parcelas', type_='foreignkey')
    op.create_foreign_key(None, 'parcelas', 'agricultores', ['agricultor_id'], ['id'], ondelete='CASCADE')
    
    # Update regiones
    op.add_column('regiones', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('regiones', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('regiones', 'codigo',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint('regiones_codigo_key', 'regiones', type_='unique')
    op.drop_constraint('regiones_nombre_key', 'regiones', type_='unique')
    op.create_index(op.f('ix_regiones_codigo'), 'regiones', ['codigo'], unique=True)
    op.create_index(op.f('ix_regiones_id'), 'regiones', ['id'], unique=False)
    op.create_index(op.f('ix_regiones_nombre'), 'regiones', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regiones_nombre'), table_name='regiones')
    op.drop_index(op.f('ix_regiones_id'), table_name='regiones')
    op.drop_index(op.f('ix_regiones_codigo'), table_name='regiones')
    op.create_unique_constraint('regiones_nombre_key', 'regiones', ['nombre'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('regiones_codigo_key', 'regiones', ['codigo'], postgresql_nulls_not_distinct=False)
    op.alter_column('regiones', 'codigo',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('regiones', 'updated_at')
    op.drop_column('regiones', 'created_at')
    op.drop_constraint(None, 'parcelas', type_='foreignkey')
    op.create_foreign_key('parcelas_agricultor_id_fkey', 'parcelas', 'agricultores', ['agricultor_id'], ['id'])
    op.drop_index(op.f('ix_parcelas_cultivo'), table_name='parcelas')
    op.drop_index('ix_parcelas_coordenadas', table_name='parcelas')
    op.drop_index(op.f('ix_parcelas_agricultor_id'), table_name='parcelas')
    op.alter_column('parcelas', 'agricultor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('parcelas', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('parcelas', 'longitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('parcelas', 'latitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('parcelas', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('parcelas', 'updated_at')
    op.drop_column('parcelas', 'created_at')
    op.create_foreign_key('fk_comuna_region', 'comunas', 'regiones', ['region_id'], ['id'])
    op.drop_constraint('uq_comuna_nombre_region', 'comunas', type_='unique')
    op.drop_index(op.f('ix_comunas_region_id'), table_name='comunas')
    op.drop_index(op.f('ix_comunas_nombre'), table_name='comunas')
    op.drop_index(op.f('ix_comunas_id'), table_name='comunas')
    op.drop_column('comunas', 'updated_at')
    op.drop_column('comunas', 'created_at')
    op.drop_constraint(None, 'balances_hidricos', type_='foreignkey')
    op.create_foreign_key('balances_hidricos_parcela_id_fkey', 'balances_hidricos', 'parcelas', ['parcela_id'], ['id'])
    op.drop_index('ix_balances_parcela_fecha', table_name='balances_hidricos')
    op.drop_index(op.f('ix_balances_hidricos_parcela_id'), table_name='balances_hidricos')
    op.drop_index(op.f('ix_balances_hidricos_fecha'), table_name='balances_hidricos')
    op.alter_column('balances_hidricos', 'parcela_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('balances_hidricos', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('balances_hidricos', 'updated_at')
    op.drop_column('balances_hidricos', 'created_at')
    op.add_column('agricultores', sa.Column('municipio_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agricultores', type_='foreignkey')
    op.create_foreign_key('agricultores_municipio_id_fkey', 'agricultores', 'municipios', ['municipio_id'], ['id'])
    op.drop_index(op.f('ix_agricultores_comuna_id'), table_name='agricultores')
    op.alter_column('agricultores', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agricultores', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agricultores', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('agricultores', 'updated_at')
    op.drop_column('agricultores', 'created_at')
    op.drop_column('agricultores', 'comuna_id')
    op.create_table('municipios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='municipios_pkey')
    )
    op.create_index('ix_municipios_nombre', 'municipios', ['nombre'], unique=False)
    op.create_index('ix_municipios_id', 'municipios', ['id'], unique=False)
    # ### end Alembic commands ###
