"""postgis_y_modelos_dga

Revision ID: 80dbaa774ac3
Revises: 0b902f51a807
Create Date: 2026-06-16 22:23:16.724743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dbaa774ac3'
down_revision: Union[str, Sequence[str], None] = '0b902f51a807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys') # IGNORAR: PostGIS requiere esta tabla
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
