"""add municipio and administrador

Revision ID: 992beaaa5feb
Revises: f15febf7007d
Create Date: 2026-05-27 01:18:43.839035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992beaaa5feb'
down_revision: Union[str, Sequence[str], None] = 'f15febf7007d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_region', 'comunas', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_region', 'comunas', 'regiones', ['region_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
