"""estaciones_hidrometricas_mop

Revision ID: e3820bbff1db
Revises: 80dbaa774ac3
Create Date: 2026-06-18 03:01:43.103576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e3820bbff1db'
down_revision: Union[str, Sequence[str], None] = 'e9045b8c2829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estaciones_hidrometricas',
    sa.Column('objectid', sa.Integer(), nullable=False),
    sa.Column('cod_estacion', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('objectid')
    )
    op.create_index('idx_estaciones_hidrometricas_geom', 'estaciones_hidrometricas', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.drop_index('idx_estaciones_hidrometricas_geom', table_name='estaciones_hidrometricas', postgresql_using='gist')
    op.drop_table('estaciones_hidrometricas')
    # ### end Alembic commands ###
