"""Initial Migration

Revision ID: e9045b8c2829
Revises: 
Create Date: 2026-06-16 01:43:19.709997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e9045b8c2829'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decretos_escasez',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_decreto', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decretos_escasez_id'), 'decretos_escasez', ['id'], unique=False)
    op.create_table('eventos_incendio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('severidad', sa.String(), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_incendio_fecha'), 'eventos_incendio', ['fecha'], unique=False)
    op.create_index(op.f('ix_eventos_incendio_id'), 'eventos_incendio', ['id'], unique=False)
    op.create_table('fuentes_hidricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuentes_hidricas_id'), 'fuentes_hidricas', ['id'], unique=False)
    op.create_index(op.f('ix_fuentes_hidricas_nombre'), 'fuentes_hidricas', ['nombre'], unique=False)
    op.create_index(op.f('ix_fuentes_hidricas_tipo'), 'fuentes_hidricas', ['tipo'], unique=False)
    op.create_table('regiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regiones_id'), 'regiones', ['id'], unique=False)
    op.create_index(op.f('ix_regiones_nombre'), 'regiones', ['nombre'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('comunas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('situacion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comunas_id'), 'comunas', ['id'], unique=False)
    op.create_index(op.f('ix_comunas_nombre'), 'comunas', ['nombre'], unique=False)
    op.create_table('consultas_territoriales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('visitor_key', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('poligono', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroide_latitud', sa.Float(), nullable=False),
    sa.Column('centroide_longitud', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('superficie_aprox_ha', sa.Float(), nullable=True),
    sa.Column('modo', sa.String(), nullable=False),
    sa.Column('guardada', sa.Boolean(), nullable=False),
    sa.Column('resumen_general', sa.Text(), nullable=True),
    sa.Column('resultado_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_territoriales_id'), 'consultas_territoriales', ['id'], unique=False)
    op.create_index(op.f('ix_consultas_territoriales_usuario_id'), 'consultas_territoriales', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_consultas_territoriales_visitor_key'), 'consultas_territoriales', ['visitor_key'], unique=False)
    op.create_table('cuencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuencas_codigo'), 'cuencas', ['codigo'], unique=False)
    op.create_index(op.f('ix_cuencas_id'), 'cuencas', ['id'], unique=False)
    op.create_index(op.f('ix_cuencas_nombre'), 'cuencas', ['nombre'], unique=False)
    op.create_index(op.f('ix_cuencas_region_id'), 'cuencas', ['region_id'], unique=False)
    op.create_table('indicadores_climaticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('et0_mm', sa.Float(), nullable=True),
    sa.Column('precipitacion_mm', sa.Float(), nullable=True),
    sa.Column('temperatura_media_c', sa.Float(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('datos_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_territoriales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicadores_climaticos_consulta_id'), 'indicadores_climaticos', ['consulta_id'], unique=False)
    op.create_index(op.f('ix_indicadores_climaticos_fecha'), 'indicadores_climaticos', ['fecha'], unique=False)
    op.create_index(op.f('ix_indicadores_climaticos_id'), 'indicadores_climaticos', ['id'], unique=False)
    op.create_table('indicadores_vegetacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('ndvi_promedio', sa.Float(), nullable=True),
    sa.Column('cobertura_vegetal', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('datos_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_territoriales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicadores_vegetacion_consulta_id'), 'indicadores_vegetacion', ['consulta_id'], unique=False)
    op.create_index(op.f('ix_indicadores_vegetacion_fecha'), 'indicadores_vegetacion', ['fecha'], unique=False)
    op.create_index(op.f('ix_indicadores_vegetacion_id'), 'indicadores_vegetacion', ['id'], unique=False)
    op.create_table('indices_sequia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('escala_temporal', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('datos_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_territoriales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indices_sequia_consulta_id'), 'indices_sequia', ['consulta_id'], unique=False)
    op.create_index(op.f('ix_indices_sequia_fecha'), 'indices_sequia', ['fecha'], unique=False)
    op.create_index(op.f('ix_indices_sequia_id'), 'indices_sequia', ['id'], unique=False)
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['comunas.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    op.create_index(op.f('ix_municipios_nombre'), 'municipios', ['nombre'], unique=False)
    op.create_table('resultados_consulta_modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('tipo_modulo', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('explicacion', sa.Text(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=True),
    sa.Column('fuentes', sa.JSON(), nullable=True),
    sa.Column('avanzado', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_territoriales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_consulta_modulos_consulta_id'), 'resultados_consulta_modulos', ['consulta_id'], unique=False)
    op.create_index(op.f('ix_resultados_consulta_modulos_id'), 'resultados_consulta_modulos', ['id'], unique=False)
    op.create_index(op.f('ix_resultados_consulta_modulos_tipo_modulo'), 'resultados_consulta_modulos', ['tipo_modulo'], unique=False)
    op.create_table('subcuencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('cuenca_id', sa.Integer(), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cuenca_id'], ['cuencas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcuencas_codigo'), 'subcuencas', ['codigo'], unique=False)
    op.create_index(op.f('ix_subcuencas_cuenca_id'), 'subcuencas', ['cuenca_id'], unique=False)
    op.create_index(op.f('ix_subcuencas_id'), 'subcuencas', ['id'], unique=False)
    op.create_index(op.f('ix_subcuencas_nombre'), 'subcuencas', ['nombre'], unique=False)
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administradores_email'), 'administradores', ['email'], unique=True)
    op.create_index(op.f('ix_administradores_id'), 'administradores', ['id'], unique=False)
    op.create_index(op.f('ix_administradores_nombre'), 'administradores', ['nombre'], unique=False)
    op.create_table('agricultores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agricultores_email'), 'agricultores', ['email'], unique=True)
    op.create_index(op.f('ix_agricultores_id'), 'agricultores', ['id'], unique=False)
    op.create_index(op.f('ix_agricultores_nombre'), 'agricultores', ['nombre'], unique=False)
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('superficie', sa.Float(), nullable=True),
    sa.Column('tipo_cultivo', sa.String(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('poligono_vertices', sa.JSON(), nullable=True),
    sa.Column('agricultor_id', sa.Integer(), nullable=True),
    sa.Column('comuna_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agricultor_id'], ['agricultores.id'], ),
    sa.ForeignKeyConstraint(['comuna_id'], ['comunas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcelas_id'), 'parcelas', ['id'], unique=False)
    op.create_index(op.f('ix_parcelas_nombre'), 'parcelas', ['nombre'], unique=False)
    op.create_table('balances_hidricos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('et0', sa.Float(), nullable=True),
    sa.Column('etc', sa.Float(), nullable=True),
    sa.Column('evapotranspiracion', sa.Float(), nullable=True),
    sa.Column('precipitacion', sa.Float(), nullable=True),
    sa.Column('riego_sugerido', sa.Float(), nullable=True),
    sa.Column('riego_sugerido_mm', sa.Float(), nullable=True),
    sa.Column('litros_recomendados', sa.Float(), nullable=True),
    sa.Column('humedad_suelo', sa.Float(), nullable=True),
    sa.Column('deficit_hidrico', sa.Float(), nullable=True),
    sa.Column('raw', sa.Float(), nullable=True),
    sa.Column('taw', sa.Float(), nullable=True),
    sa.Column('estado_hidrico', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balances_hidricos_fecha'), 'balances_hidricos', ['fecha'], unique=False)
    op.create_index(op.f('ix_balances_hidricos_id'), 'balances_hidricos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balances_hidricos_id'), table_name='balances_hidricos')
    op.drop_index(op.f('ix_balances_hidricos_fecha'), table_name='balances_hidricos')
    op.drop_table('balances_hidricos')
    op.drop_index(op.f('ix_parcelas_nombre'), table_name='parcelas')
    op.drop_index(op.f('ix_parcelas_id'), table_name='parcelas')
    op.drop_table('parcelas')
    op.drop_index(op.f('ix_agricultores_nombre'), table_name='agricultores')
    op.drop_index(op.f('ix_agricultores_id'), table_name='agricultores')
    op.drop_index(op.f('ix_agricultores_email'), table_name='agricultores')
    op.drop_table('agricultores')
    op.drop_index(op.f('ix_administradores_nombre'), table_name='administradores')
    op.drop_index(op.f('ix_administradores_id'), table_name='administradores')
    op.drop_index(op.f('ix_administradores_email'), table_name='administradores')
    op.drop_table('administradores')
    op.drop_index(op.f('ix_subcuencas_nombre'), table_name='subcuencas')
    op.drop_index(op.f('ix_subcuencas_id'), table_name='subcuencas')
    op.drop_index(op.f('ix_subcuencas_cuenca_id'), table_name='subcuencas')
    op.drop_index(op.f('ix_subcuencas_codigo'), table_name='subcuencas')
    op.drop_table('subcuencas')
    op.drop_index(op.f('ix_resultados_consulta_modulos_tipo_modulo'), table_name='resultados_consulta_modulos')
    op.drop_index(op.f('ix_resultados_consulta_modulos_id'), table_name='resultados_consulta_modulos')
    op.drop_index(op.f('ix_resultados_consulta_modulos_consulta_id'), table_name='resultados_consulta_modulos')
    op.drop_table('resultados_consulta_modulos')
    op.drop_index(op.f('ix_municipios_nombre'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_table('municipios')
    op.drop_index(op.f('ix_indices_sequia_id'), table_name='indices_sequia')
    op.drop_index(op.f('ix_indices_sequia_fecha'), table_name='indices_sequia')
    op.drop_index(op.f('ix_indices_sequia_consulta_id'), table_name='indices_sequia')
    op.drop_table('indices_sequia')
    op.drop_index(op.f('ix_indicadores_vegetacion_id'), table_name='indicadores_vegetacion')
    op.drop_index(op.f('ix_indicadores_vegetacion_fecha'), table_name='indicadores_vegetacion')
    op.drop_index(op.f('ix_indicadores_vegetacion_consulta_id'), table_name='indicadores_vegetacion')
    op.drop_table('indicadores_vegetacion')
    op.drop_index(op.f('ix_indicadores_climaticos_id'), table_name='indicadores_climaticos')
    op.drop_index(op.f('ix_indicadores_climaticos_fecha'), table_name='indicadores_climaticos')
    op.drop_index(op.f('ix_indicadores_climaticos_consulta_id'), table_name='indicadores_climaticos')
    op.drop_table('indicadores_climaticos')
    op.drop_index(op.f('ix_cuencas_region_id'), table_name='cuencas')
    op.drop_index(op.f('ix_cuencas_nombre'), table_name='cuencas')
    op.drop_index(op.f('ix_cuencas_id'), table_name='cuencas')
    op.drop_index(op.f('ix_cuencas_codigo'), table_name='cuencas')
    op.drop_table('cuencas')
    op.drop_index(op.f('ix_consultas_territoriales_visitor_key'), table_name='consultas_territoriales')
    op.drop_index(op.f('ix_consultas_territoriales_usuario_id'), table_name='consultas_territoriales')
    op.drop_index(op.f('ix_consultas_territoriales_id'), table_name='consultas_territoriales')
    op.drop_table('consultas_territoriales')
    op.drop_index(op.f('ix_comunas_nombre'), table_name='comunas')
    op.drop_index(op.f('ix_comunas_id'), table_name='comunas')
    op.drop_table('comunas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_regiones_nombre'), table_name='regiones')
    op.drop_index(op.f('ix_regiones_id'), table_name='regiones')
    op.drop_table('regiones')
    op.drop_index(op.f('ix_fuentes_hidricas_tipo'), table_name='fuentes_hidricas')
    op.drop_index(op.f('ix_fuentes_hidricas_nombre'), table_name='fuentes_hidricas')
    op.drop_index(op.f('ix_fuentes_hidricas_id'), table_name='fuentes_hidricas')
    op.drop_table('fuentes_hidricas')
    op.drop_index(op.f('ix_eventos_incendio_id'), table_name='eventos_incendio')
    op.drop_index(op.f('ix_eventos_incendio_fecha'), table_name='eventos_incendio')
    op.drop_table('eventos_incendio')
    op.drop_index(op.f('ix_decretos_escasez_id'), table_name='decretos_escasez')
    op.drop_table('decretos_escasez')
    # ### end Alembic commands ###
