"""migracion inicial

Revision ID: f15febf7007d
Revises: 66148a459850
Create Date: 2026-05-26 18:54:53.472060
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f15febf7007d'
down_revision = '66148a459850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['comunas.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    op.create_index(op.f('ix_municipios_nombre'), 'municipios', ['nombre'], unique=False)
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administradores_email'), 'administradores', ['email'], unique=True)
    op.create_index(op.f('ix_administradores_id'), 'administradores', ['id'], unique=False)
    op.create_index(op.f('ix_administradores_nombre'), 'administradores', ['nombre'], unique=False)
    op.add_column('agricultores', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('agricultores', sa.Column('municipio_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_agricultores_comuna_id'), table_name='agricultores')
    op.drop_constraint(op.f('agricultores_comuna_id_fkey'), 'agricultores', type_='foreignkey')
    op.create_foreign_key(None, 'agricultores', 'municipios', ['municipio_id'], ['id'])
    op.drop_column('agricultores', 'created_at')
    op.drop_column('agricultores', 'comuna_id')
    op.drop_column('agricultores', 'updated_at')
    op.add_column('balances_hidricos', sa.Column('evapotranspiracion', sa.Float(), nullable=True))
    op.add_column('balances_hidricos', sa.Column('riego_sugerido', sa.Float(), nullable=True))
    op.alter_column('balances_hidricos', 'parcela_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_balances_hidricos_parcela_id'), table_name='balances_hidricos')
    op.drop_index(op.f('ix_balances_parcela_fecha'), table_name='balances_hidricos')
    op.drop_constraint(op.f('balances_hidricos_parcela_id_fkey'), 'balances_hidricos', type_='foreignkey')
    op.create_foreign_key(None, 'balances_hidricos', 'parcelas', ['parcela_id'], ['id'])
    op.drop_column('balances_hidricos', 'riego')
    op.drop_column('balances_hidricos', 'updated_at')
    op.drop_column('balances_hidricos', 'et_o')
    op.drop_column('balances_hidricos', 'created_at')
    op.drop_column('balances_hidricos', 'evapotranspiracion_real')
    op.add_column('comunas', sa.Column('situacion', sa.String(), nullable=True))
    op.alter_column('comunas', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_comunas_region_id'), table_name='comunas')
    op.drop_constraint(op.f('uq_comuna_nombre_region'), 'comunas', type_='unique')
    op.drop_constraint(op.f('comunas_region_id_fkey'), 'comunas', type_='foreignkey')
    op.create_foreign_key(None, 'comunas', 'regiones', ['region_id'], ['id'])
    op.drop_column('comunas', 'created_at')
    op.drop_column('comunas', 'updated_at')
    op.add_column('parcelas', sa.Column('comuna_id', sa.Integer(), nullable=True))
    op.add_column('parcelas', sa.Column('superficie', sa.Float(), nullable=True))
    op.add_column('parcelas', sa.Column('tipo_cultivo', sa.String(), nullable=True))
    op.alter_column('parcelas', 'agricultor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('parcelas', 'latitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('parcelas', 'longitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_parcelas_agricultor_id'), table_name='parcelas')
    op.drop_index(op.f('ix_parcelas_coordenadas'), table_name='parcelas')
    op.drop_index(op.f('ix_parcelas_cultivo'), table_name='parcelas')
    op.drop_constraint(op.f('parcelas_agricultor_id_fkey'), 'parcelas', type_='foreignkey')
    op.create_foreign_key(None, 'parcelas', 'comunas', ['comuna_id'], ['id'])
    op.create_foreign_key(None, 'parcelas', 'agricultores', ['agricultor_id'], ['id'])
    op.drop_column('parcelas', 'created_at')
    op.drop_column('parcelas', 'area')
    op.drop_column('parcelas', 'cultivo')
    op.drop_column('parcelas', 'updated_at')
    op.drop_index(op.f('ix_regiones_codigo'), table_name='regiones')
    op.drop_index(op.f('ix_regiones_nombre'), table_name='regiones')
    op.create_index(op.f('ix_regiones_nombre'), 'regiones', ['nombre'], unique=False)
    op.drop_column('regiones', 'codigo')
    op.drop_column('regiones', 'created_at')
    op.drop_column('regiones', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regiones', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('regiones', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('regiones', sa.Column('codigo', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_regiones_nombre'), table_name='regiones')
    op.create_index(op.f('ix_regiones_nombre'), 'regiones', ['nombre'], unique=True)
    op.create_index(op.f('ix_regiones_codigo'), 'regiones', ['codigo'], unique=True)
    op.add_column('parcelas', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('parcelas', sa.Column('cultivo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parcelas', sa.Column('area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('parcelas', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parcelas', type_='foreignkey')
    op.drop_constraint(None, 'parcelas', type_='foreignkey')
    op.create_foreign_key(op.f('parcelas_agricultor_id_fkey'), 'parcelas', 'agricultores', ['agricultor_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_parcelas_cultivo'), 'parcelas', ['cultivo'], unique=False)
    op.create_index(op.f('ix_parcelas_coordenadas'), 'parcelas', ['latitud', 'longitud'], unique=False)
    op.create_index(op.f('ix_parcelas_agricultor_id'), 'parcelas', ['agricultor_id'], unique=False)
    op.alter_column('parcelas', 'longitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('parcelas', 'latitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('parcelas', 'agricultor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('parcelas', 'tipo_cultivo')
    op.drop_column('parcelas', 'superficie')
    op.drop_column('parcelas', 'comuna_id')
    op.add_column('comunas', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('comunas', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comunas', type_='foreignkey')
    op.create_foreign_key(op.f('comunas_region_id_fkey'), 'comunas', 'regiones', ['region_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_comuna_nombre_region'), 'comunas', ['nombre', 'region_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_comunas_region_id'), 'comunas', ['region_id'], unique=False)
    op.alter_column('comunas', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comunas', 'situacion')
    op.add_column('balances_hidricos', sa.Column('evapotranspiracion_real', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('balances_hidricos', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('balances_hidricos', sa.Column('et_o', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('balances_hidricos', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('balances_hidricos', sa.Column('riego', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'balances_hidricos', type_='foreignkey')
    op.create_foreign_key(op.f('balances_hidricos_parcela_id_fkey'), 'balances_hidricos', 'parcelas', ['parcela_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_balances_parcela_fecha'), 'balances_hidricos', ['parcela_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_balances_hidricos_parcela_id'), 'balances_hidricos', ['parcela_id'], unique=False)
    op.alter_column('balances_hidricos', 'parcela_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('balances_hidricos', 'riego_sugerido')
    op.drop_column('balances_hidricos', 'evapotranspiracion')
    op.add_column('agricultores', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('agricultores', sa.Column('comuna_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agricultores', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agricultores', type_='foreignkey')
    op.create_foreign_key(op.f('agricultores_comuna_id_fkey'), 'agricultores', 'comunas', ['comuna_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_agricultores_comuna_id'), 'agricultores', ['comuna_id'], unique=False)
    op.drop_column('agricultores', 'municipio_id')
    op.drop_column('agricultores', 'is_active')
    op.drop_index(op.f('ix_administradores_nombre'), table_name='administradores')
    op.drop_index(op.f('ix_administradores_id'), table_name='administradores')
    op.drop_index(op.f('ix_administradores_email'), table_name='administradores')
    op.drop_table('administradores')
    op.drop_index(op.f('ix_municipios_nombre'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_table('municipios')
    # ### end Alembic commands ###
